spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy 
    url: jdbc:log4jdbc:oracle:thin:@117.114.153.12:1521:catvdb
    username: netinfo
    password: netcatv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  session:
    store-type: none
logging:
  level: 
    root: WARN
    org:
      springframework:
        security: WARN
        web: ERROR    
      hibernate: WARN
cas:
  casServerLoginUrl: http://172.16.8.35/authsrv
  appServerName: http://localhost