CREATE USER netinfo IDENTIFIED BY netinfo
 DEFAULT TABLESPACE NETINFODB
 TEMPORARY TABLESPACE TEMP
 PROFILE "DEFAULT";

GRANT "CONNECT" TO netinfo;
GRANT "DBA" TO netinfo;
GRANT "RESOURCE" TO netinfo;
ALTER USER netinfo DEFAULT ROLE "CONNECT", "DBA", "RESOURCE";